pages:
  stage: deploy
  script:
    - mkdir .public
    - cp -r * .public/
    - rm -rf .public/.git
    - mv .public public
  artifacts:
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == "master"
    - if: $CI_COMMIT_BRANCH == "main"
